os:
- Visual Studio 2015
- Visual Studio 2017

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DOPTIONAL_WERROR=ON ..
  - cmake --build .
  - C:\projects\optional\build\Debug\tests.exe
